remote_theme: yous/whiteglass
title: Test stastic
author: singchan
description: A test to admin your Jekyll site with Stastic
baseurl: /meretricious_teacher
url: 'https://yous.github.io'
lang: en
twitter_username: null
twitter_image: null
facebook_app_id: null
facebook_image: null
google_analytics: null
comments: false
excerpt_separator: <!-- more -->
